# Setup
title:               Justin Lamb
tagline:             'Blog'
description:         'Personal Blog'
url:                 https://blog.justinlamb.org
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Justin Lamb
  url:               https://ruby.social/@justinlamb
  email:             ''

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
